# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\STUFF\IDAT\Ciclo II\PROYECTO_FINAL\ui\admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\STUFF\\IDAT\\Ciclo II\\PROYECTO_FINAL\\ui\\../assets/python.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    font-family: century-ghotic;\n"
"}\n"
"\n"
"QWidget#background{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgb(20, 20, 20), stop:1 rgb(80, 80, 80));\n"
"}\n"
"\n"
"QFrame#frame_main{\n"
"    background-color: rgb(20, 20, 20);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#frame_inve{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#frame_prod{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#edit_stock_frame {\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(152, 152, 152);\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QMessageBox{\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"    color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    color: rgb(230, 230, 230);\n"
"    gridline-color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-right: 8px solid rgb(20, 20, 20);\n"
"    border-left: 8px solid rgb(20, 20, 20);\n"
"}\n"
"\n"
"QTableWidget QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(152, 152, 152);\n"
"    width: 15px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(152, 152, 152);\n"
"    height: 15px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::add-page:vertical, QTableWidget QScrollBar::sub-page:vertical,\n"
"QTableWidget QScrollBar::add-page:horizontal, QTableWidget QScrollBar::sub-page:horizontal {\n"
"    background: rgb(152, 152, 152);\n"
"}\n"
"\n"
"QTableWidget QScrollBar::handle:vertical, QTableWidget QScrollBar::handle:horizontal {\n"
"    background: rgb(44, 44, 44);\n"
"    margin: 2px 2.5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::sub-line:vertical, QTableWidget QScrollBar::add-line:vertical,\n"
"QTableWidget QScrollBar::sub-line:horizontal, QTableWidget QScrollBar::add-line:horizontal {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QFrame#edit_stock_frame QLabel {\n"
"    color: black;\n"
"}\n"
"\n"
"QLabel#lbl_id_nombre {\n"
"    font-family: century-ghotic;\n"
"    font-size: 18px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton#btn_apply{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#btn_apply:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QPushButton#btn_apply:pressed {\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"QSpinBox {\n"
"    font-size: 18px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: #000000;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox {\n"
"    font-size: 18px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: #000000;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    font-size: 12px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: #000000;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    font-size: 12px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: #000000;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #ffffff;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    background-color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 4px solid gray;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton#btn_delete {\n"
"    color: white;\n"
"    background-color: black;\n"
"    border: 4px solid white;\n"
"}\n"
"\n"
"QPushButton#btn_delete:hover {\n"
"    color: black;\n"
"    background-color: white;\n"
"}")
        self.background = QtWidgets.QWidget(MainWindow)
        self.background.setStyleSheet("")
        self.background.setObjectName("background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_fondo = QtWidgets.QFrame(self.background)
        self.frame_fondo.setMinimumSize(QtCore.QSize(1366, 768))
        self.frame_fondo.setMaximumSize(QtCore.QSize(1633, 768))
        self.frame_fondo.setStyleSheet("")
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.frame_main = QtWidgets.QFrame(self.frame_fondo)
        self.frame_main.setGeometry(QtCore.QRect(20, 20, 1331, 731))
        self.frame_main.setStyleSheet("QTableWidget QScrollBar::sub-line:vertical, QTableWidget QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTableWidget QScrollBar::up-arrow:vertical, QTableWidget QScrollBar::down-arrow:vertical {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.tblProducto = QtWidgets.QTableWidget(self.frame_main)
        self.tblProducto.setEnabled(True)
        self.tblProducto.setGeometry(QtCore.QRect(40, 190, 1261, 521))
        self.tblProducto.setStyleSheet("")
        self.tblProducto.setObjectName("tblProducto")
        self.tblProducto.setColumnCount(10)
        self.tblProducto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProducto.setHorizontalHeaderItem(9, item)
        self.tblProducto.verticalHeader().setCascadingSectionResizes(False)
        self.txtBuscar = QtWidgets.QLineEdit(self.frame_main)
        self.txtBuscar.setGeometry(QtCore.QRect(310, 100, 281, 41))
        self.txtBuscar.setObjectName("txtBuscar")
        self.lbl_title = QtWidgets.QLabel(self.frame_main)
        self.lbl_title.setGeometry(QtCore.QRect(30, 10, 441, 51))
        self.lbl_title.setObjectName("lbl_title")
        self.edit_stock_frame = QtWidgets.QFrame(self.frame_main)
        self.edit_stock_frame.setGeometry(QtCore.QRect(690, 90, 551, 71))
        self.edit_stock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_stock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_stock_frame.setObjectName("edit_stock_frame")
        self.lbl_id_nombre = QtWidgets.QLabel(self.edit_stock_frame)
        self.lbl_id_nombre.setGeometry(QtCore.QRect(20, 0, 511, 71))
        self.lbl_id_nombre.setObjectName("lbl_id_nombre")
        self.tblInventarista = QtWidgets.QTableWidget(self.frame_main)
        self.tblInventarista.setEnabled(True)
        self.tblInventarista.setGeometry(QtCore.QRect(40, 190, 1261, 521))
        self.tblInventarista.setStyleSheet("")
        self.tblInventarista.setObjectName("tblInventarista")
        self.tblInventarista.setColumnCount(14)
        self.tblInventarista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInventarista.setHorizontalHeaderItem(13, item)
        self.tblInventarista.verticalHeader().setCascadingSectionResizes(False)
        self.btn_to_login = QtWidgets.QPushButton(self.frame_main)
        self.btn_to_login.setGeometry(QtCore.QRect(1280, 0, 50, 50))
        self.btn_to_login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\STUFF\\IDAT\\Ciclo II\\PROYECTO_FINAL\\ui\\../assets/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_to_login.setIcon(icon1)
        self.btn_to_login.setIconSize(QtCore.QSize(30, 30))
        self.btn_to_login.setObjectName("btn_to_login")
        self.btn_edit = QtWidgets.QPushButton(self.frame_main)
        self.btn_edit.setGeometry(QtCore.QRect(690, 30, 141, 41))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_add = QtWidgets.QPushButton(self.frame_main)
        self.btn_add.setGeometry(QtCore.QRect(850, 30, 141, 41))
        self.btn_add.setObjectName("btn_add")
        self.btn_delete = QtWidgets.QPushButton(self.frame_main)
        self.btn_delete.setGeometry(QtCore.QRect(1100, 30, 141, 41))
        self.btn_delete.setObjectName("btn_delete")
        self.rb_producto = QtWidgets.QRadioButton(self.frame_main)
        self.rb_producto.setGeometry(QtCore.QRect(80, 120, 191, 41))
        self.rb_producto.setObjectName("rb_producto")
        self.rb_inven = QtWidgets.QRadioButton(self.frame_main)
        self.rb_inven.setGeometry(QtCore.QRect(80, 80, 191, 41))
        self.rb_inven.setObjectName("rb_inven")
        self.frame_inve = QtWidgets.QFrame(self.frame_fondo)
        self.frame_inve.setGeometry(QtCore.QRect(550, 0, 591, 521))
        self.frame_inve.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inve.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inve.setObjectName("frame_inve")
        self.lbl_titulo_inv = QtWidgets.QLabel(self.frame_inve)
        self.lbl_titulo_inv.setGeometry(QtCore.QRect(40, 30, 501, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo_inv.setFont(font)
        self.lbl_titulo_inv.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo_inv.setObjectName("lbl_titulo_inv")
        self.txt_id_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_id_inv.setGeometry(QtCore.QRect(40, 90, 211, 20))
        self.txt_id_inv.setObjectName("txt_id_inv")
        self.txt_ape_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_ape_inv.setGeometry(QtCore.QRect(40, 140, 211, 20))
        self.txt_ape_inv.setObjectName("txt_ape_inv")
        self.txt_nom_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_nom_inv.setGeometry(QtCore.QRect(40, 190, 211, 20))
        self.txt_nom_inv.setObjectName("txt_nom_inv")
        self.txt_dir_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_dir_inv.setGeometry(QtCore.QRect(40, 340, 211, 20))
        self.txt_dir_inv.setObjectName("txt_dir_inv")
        self.txt_doc_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_doc_inv.setGeometry(QtCore.QRect(40, 290, 211, 20))
        self.txt_doc_inv.setObjectName("txt_doc_inv")
        self.txt_ubi_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_ubi_inv.setGeometry(QtCore.QRect(40, 390, 211, 20))
        self.txt_ubi_inv.setObjectName("txt_ubi_inv")
        self.txt_tel_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_tel_inv.setGeometry(QtCore.QRect(330, 90, 211, 20))
        self.txt_tel_inv.setObjectName("txt_tel_inv")
        self.txt_mail_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_mail_inv.setGeometry(QtCore.QRect(330, 140, 211, 20))
        self.txt_mail_inv.setObjectName("txt_mail_inv")
        self.txt_pass_inv = QtWidgets.QLineEdit(self.frame_inve)
        self.txt_pass_inv.setGeometry(QtCore.QRect(330, 390, 211, 20))
        self.txt_pass_inv.setObjectName("txt_pass_inv")
        self.cbo_doc = QtWidgets.QComboBox(self.frame_inve)
        self.cbo_doc.setGeometry(QtCore.QRect(150, 230, 101, 31))
        self.cbo_doc.setObjectName("cbo_doc")
        self.cbo_doc.addItem("")
        self.cbo_doc.addItem("")
        self.cbo_doc.addItem("")
        self.date_nac = QtWidgets.QDateEdit(self.frame_inve)
        self.date_nac.setGeometry(QtCore.QRect(440, 180, 101, 31))
        self.date_nac.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2005, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_nac.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1950, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_nac.setObjectName("date_nac")
        self.cbo_sexo = QtWidgets.QComboBox(self.frame_inve)
        self.cbo_sexo.setGeometry(QtCore.QRect(440, 230, 101, 31))
        self.cbo_sexo.setObjectName("cbo_sexo")
        self.cbo_sexo.addItem("")
        self.cbo_sexo.addItem("")
        self.cbo_turno = QtWidgets.QComboBox(self.frame_inve)
        self.cbo_turno.setGeometry(QtCore.QRect(440, 330, 101, 31))
        self.cbo_turno.setObjectName("cbo_turno")
        self.cbo_turno.addItem("")
        self.cbo_turno.addItem("")
        self.cbo_turno.addItem("")
        self.label = QtWidgets.QLabel(self.frame_inve)
        self.label.setGeometry(QtCore.QRect(40, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_inve)
        self.label_2.setGeometry(QtCore.QRect(330, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_inve)
        self.label_3.setGeometry(QtCore.QRect(330, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_inve)
        self.label_4.setGeometry(QtCore.QRect(330, 340, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_inve)
        self.label_5.setGeometry(QtCore.QRect(330, 290, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_acep_inv = QtWidgets.QPushButton(self.frame_inve)
        self.btn_acep_inv.setGeometry(QtCore.QRect(320, 450, 171, 41))
        self.btn_acep_inv.setObjectName("btn_acep_inv")
        self.btn_canc_inv = QtWidgets.QPushButton(self.frame_inve)
        self.btn_canc_inv.setGeometry(QtCore.QRect(100, 450, 171, 41))
        self.btn_canc_inv.setObjectName("btn_canc_inv")
        self.spb_sueldo = QtWidgets.QDoubleSpinBox(self.frame_inve)
        self.spb_sueldo.setGeometry(QtCore.QRect(440, 280, 101, 31))
        self.spb_sueldo.setMinimum(500.0)
        self.spb_sueldo.setMaximum(5000.0)
        self.spb_sueldo.setSingleStep(100.0)
        self.spb_sueldo.setObjectName("spb_sueldo")
        self.frame_prod = QtWidgets.QFrame(self.frame_fondo)
        self.frame_prod.setGeometry(QtCore.QRect(60, 10, 591, 371))
        self.frame_prod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_prod.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_prod.setObjectName("frame_prod")
        self.lbl_titulo_prod = QtWidgets.QLabel(self.frame_prod)
        self.lbl_titulo_prod.setGeometry(QtCore.QRect(40, 30, 501, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo_prod.setFont(font)
        self.lbl_titulo_prod.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo_prod.setObjectName("lbl_titulo_prod")
        self.txt_id_prod = QtWidgets.QLineEdit(self.frame_prod)
        self.txt_id_prod.setGeometry(QtCore.QRect(40, 90, 211, 20))
        self.txt_id_prod.setObjectName("txt_id_prod")
        self.txt_desc_prod = QtWidgets.QLineEdit(self.frame_prod)
        self.txt_desc_prod.setGeometry(QtCore.QRect(40, 140, 211, 20))
        self.txt_desc_prod.setObjectName("txt_desc_prod")
        self.date_ing = QtWidgets.QDateEdit(self.frame_prod)
        self.date_ing.setGeometry(QtCore.QRect(440, 180, 101, 31))
        self.date_ing.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2090, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_ing.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_ing.setObjectName("date_ing")
        self.cbo_estado_prod = QtWidgets.QComboBox(self.frame_prod)
        self.cbo_estado_prod.setGeometry(QtCore.QRect(150, 230, 101, 31))
        self.cbo_estado_prod.setObjectName("cbo_estado_prod")
        self.cbo_estado_prod.addItem("")
        self.cbo_estado_prod.addItem("")
        self.cbo_subfam_prod = QtWidgets.QComboBox(self.frame_prod)
        self.cbo_subfam_prod.setGeometry(QtCore.QRect(440, 230, 101, 31))
        self.cbo_subfam_prod.setObjectName("cbo_subfam_prod")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.cbo_subfam_prod.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame_prod)
        self.label_7.setGeometry(QtCore.QRect(330, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_prod)
        self.label_8.setGeometry(QtCore.QRect(40, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_prod)
        self.label_9.setGeometry(QtCore.QRect(330, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_prod)
        self.label_10.setGeometry(QtCore.QRect(40, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btn_acep_prod = QtWidgets.QPushButton(self.frame_prod)
        self.btn_acep_prod.setGeometry(QtCore.QRect(320, 300, 171, 41))
        self.btn_acep_prod.setObjectName("btn_acep_prod")
        self.btn_canc_prod = QtWidgets.QPushButton(self.frame_prod)
        self.btn_canc_prod.setGeometry(QtCore.QRect(100, 300, 171, 41))
        self.btn_canc_prod.setObjectName("btn_canc_prod")
        self.spb_precio_prod = QtWidgets.QDoubleSpinBox(self.frame_prod)
        self.spb_precio_prod.setGeometry(QtCore.QRect(150, 180, 101, 31))
        self.spb_precio_prod.setMinimum(1.0)
        self.spb_precio_prod.setMaximum(1000.0)
        self.spb_precio_prod.setSingleStep(10.0)
        self.spb_precio_prod.setProperty("value", 50.0)
        self.spb_precio_prod.setObjectName("spb_precio_prod")
        self.spb_stock = QtWidgets.QSpinBox(self.frame_prod)
        self.spb_stock.setGeometry(QtCore.QRect(440, 80, 101, 31))
        self.spb_stock.setMaximum(500)
        self.spb_stock.setSingleStep(10)
        self.spb_stock.setProperty("value", 50)
        self.spb_stock.setObjectName("spb_stock")
        self.label_11 = QtWidgets.QLabel(self.frame_prod)
        self.label_11.setGeometry(QtCore.QRect(330, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spb_peso_prod = QtWidgets.QDoubleSpinBox(self.frame_prod)
        self.spb_peso_prod.setGeometry(QtCore.QRect(440, 130, 101, 31))
        self.spb_peso_prod.setMinimum(0.1)
        self.spb_peso_prod.setMaximum(50.0)
        self.spb_peso_prod.setSingleStep(0.5)
        self.spb_peso_prod.setProperty("value", 1.0)
        self.spb_peso_prod.setObjectName("spb_peso_prod")
        self.label_12 = QtWidgets.QLabel(self.frame_prod)
        self.label_12.setGeometry(QtCore.QRect(330, 140, 111, 21))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.frame_fondo)
        MainWindow.setCentralWidget(self.background)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INVENTIVA STOCK"))
        item = self.tblProducto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblProducto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descripción"))
        item = self.tblProducto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tblProducto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.tblProducto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tblProducto.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Peso"))
        item = self.tblProducto.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ingreso"))
        item = self.tblProducto.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Subfamilia"))
        item = self.tblProducto.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Familia"))
        item = self.tblProducto.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Línea"))
        self.txtBuscar.setPlaceholderText(_translate("MainWindow", "Buscar..."))
        self.lbl_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Inventiva Stock Admin</span></p></body></html>"))
        self.lbl_id_nombre.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ID12345: NOMBRE</span></p></body></html>"))
        item = self.tblInventarista.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblInventarista.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Contraseña"))
        item = self.tblInventarista.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.tblInventarista.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.tblInventarista.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Documento"))
        item = self.tblInventarista.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Identificación"))
        item = self.tblInventarista.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dirección"))
        item = self.tblInventarista.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ubigeo"))
        item = self.tblInventarista.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Teléfono"))
        item = self.tblInventarista.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Correo"))
        item = self.tblInventarista.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Fecha nac."))
        item = self.tblInventarista.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Sexo"))
        item = self.tblInventarista.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Sueldo"))
        item = self.tblInventarista.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Turno"))
        self.btn_edit.setText(_translate("MainWindow", "Editar"))
        self.btn_add.setText(_translate("MainWindow", "Agregar"))
        self.btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.rb_producto.setText(_translate("MainWindow", "Productos"))
        self.rb_inven.setText(_translate("MainWindow", "Inventaristas"))
        self.lbl_titulo_inv.setText(_translate("MainWindow", "EDITAR USUARIO"))
        self.txt_id_inv.setPlaceholderText(_translate("MainWindow", "ID1234"))
        self.txt_ape_inv.setPlaceholderText(_translate("MainWindow", "Apellidos"))
        self.txt_nom_inv.setPlaceholderText(_translate("MainWindow", "Nombres"))
        self.txt_dir_inv.setPlaceholderText(_translate("MainWindow", "Dirección"))
        self.txt_doc_inv.setPlaceholderText(_translate("MainWindow", "Número de documento"))
        self.txt_ubi_inv.setPlaceholderText(_translate("MainWindow", "Ubigeo"))
        self.txt_tel_inv.setPlaceholderText(_translate("MainWindow", "Teléfono"))
        self.txt_mail_inv.setPlaceholderText(_translate("MainWindow", "Correo"))
        self.txt_pass_inv.setPlaceholderText(_translate("MainWindow", "Password"))
        self.cbo_doc.setItemText(0, _translate("MainWindow", "DNI"))
        self.cbo_doc.setItemText(1, _translate("MainWindow", "Pasaporte"))
        self.cbo_doc.setItemText(2, _translate("MainWindow", "Carné de Extranjería"))
        self.cbo_sexo.setItemText(0, _translate("MainWindow", "M"))
        self.cbo_sexo.setItemText(1, _translate("MainWindow", "F"))
        self.cbo_turno.setItemText(0, _translate("MainWindow", "Mañana"))
        self.cbo_turno.setItemText(1, _translate("MainWindow", "Tarde"))
        self.cbo_turno.setItemText(2, _translate("MainWindow", "Noche"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\"> Documento</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Fecha Nac.</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Sexo</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Turno</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Sueldo</span></p></body></html>"))
        self.btn_acep_inv.setText(_translate("MainWindow", "Aceptar"))
        self.btn_canc_inv.setText(_translate("MainWindow", "Cancelar"))
        self.lbl_titulo_prod.setText(_translate("MainWindow", "EDITAR PRODUCTO"))
        self.txt_id_prod.setPlaceholderText(_translate("MainWindow", "ID1234"))
        self.txt_desc_prod.setPlaceholderText(_translate("MainWindow", "Descripcion"))
        self.cbo_estado_prod.setItemText(0, _translate("MainWindow", "Activo"))
        self.cbo_estado_prod.setItemText(1, _translate("MainWindow", "Inactivo"))
        self.cbo_subfam_prod.setItemText(0, _translate("MainWindow", "COTILLÓN"))
        self.cbo_subfam_prod.setItemText(1, _translate("MainWindow", "ENTRETENIMIENTO"))
        self.cbo_subfam_prod.setItemText(2, _translate("MainWindow", "MUÑECAS"))
        self.cbo_subfam_prod.setItemText(3, _translate("MainWindow", "OTROS JUEGOS"))
        self.cbo_subfam_prod.setItemText(4, _translate("MainWindow", "PERSONAJES"))
        self.cbo_subfam_prod.setItemText(5, _translate("MainWindow", "TRANSPORTES"))
        self.cbo_subfam_prod.setItemText(6, _translate("MainWindow", "ARMABLES"))
        self.cbo_subfam_prod.setItemText(7, _translate("MainWindow", "DIDÁCTICOS"))
        self.cbo_subfam_prod.setItemText(8, _translate("MainWindow", "JUEGOS MUSICALES"))
        self.cbo_subfam_prod.setItemText(9, _translate("MainWindow", "SIN LICENCIA"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Fecha ingreso</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Estado</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Stock</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Precio</span></p></body></html>"))
        self.btn_acep_prod.setText(_translate("MainWindow", "Aceptar"))
        self.btn_canc_prod.setText(_translate("MainWindow", "Cancelar"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Subfamilia</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e6e6e6;\">Peso</span></p></body></html>"))
